#!/usr/bin/env bash
# script to install nginx and configure a web-01 server

# install Nginx
apt-get update -y
apt-get install nginx -y

# adjust the firewall to allow port 80
ufw allow 'Nginx HTTP'

# create new document root directory

mkdir -p /etc/nginx/html

# create 404 page for the site
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# create server block and add directives
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	error_page 404 /404.html;
	location /404 {
		root /usr/share/nginx/html;
		internal;
	}
}
" > /etc/nginx/sites-available/default

service nginx restart

