#!/usr/bin/env bash
# Installs Nginx with the following configurations:
apt-get update
apt-get install -y nginx

hostname=$(hostname)
mkdir /etc/nginx/html
echo "Hello World" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     add_header X-Served-By "$hostname";
}
" > /etc/nginx/sites-available/default

service nginx restart
